#!/bin/bash

options=(
	style=round
	width=6.0
	hidpi=off
	# Everforest Dark - Accent Green
	active_color=0xff82b474  # Everforest 'green' accent color
	inactive_color=0xff475059 # Everforest 'bg1' or 'bg_dim' (background variant) - a desaturated dark blue/grey
)

borders "${options[@]}"
