return {
  'folke/which-key.nvim',
  event = 'VimEnter',
  opts = {
    delay = 0,
    icons = {
      mappings = vim.g.have_nerd_font,
      keys = vim.g.have_nerd_font and {} or {
        Up = '<Up> ',
        Down = '<Down> ',
        Left = '<Left> ',
        Right = '<Right> ',
        C = '<C-…> ',
        M = '<M-…> ',
        D = '<D-…> ',
        S = '<S-…> ',
        CR = '<CR> ',
        Esc = '<Esc> ',
        ScrollWheelDown = '<ScrollWheelDown> ',
        ScrollWheelUp = '<ScrollWheelUp> ',
        NL = '<NL> ',
        BS = '<BS> ',
        Space = '<Space> ',
        Tab = '<Tab> ',
        F1 = '<F1>',
        F2 = '<F2>',
        F3 = '<F3>',
        F4 = '<F4>',
        F5 = '<F5>',
        F6 = '<F6>',
        F7 = '<F7>',
        F8 = '<F8>',
        F9 = '<F9>',
        F10 = '<F10>',
        F11 = '<F11>',
        F12 = '<F12>',
      },
    },
    spec = {
      { '<leader>s', group = '[S]earch' },
      { '<leader>t', group = '[T]oggle' },
      { '<leader>b', group = '[B]uffer' },
      { '<leader>g', group = '[G]it' },
      { '<leader>h', group = 'Git [H]unk', mode = { 'n', 'v' } },
      { '<leader>hs', 'Git [S]tage hunk', mode = { 'n', 'v' } },
      { '<leader>hr', 'Git [R]eset hunk', mode = { 'n', 'v' } },
      { '<leader>hS', 'Git [S]tage buffer' },
      { '<leader>hR', 'Git [R]eset buffer' },
      { '<leader>hu', 'Git [U]ndo stage hunk' },
      { '<leader>hp', 'Git [P]review hunk' },
      { '<leader>hb', 'Git [B]lame line' },
      { '<leader>hd', 'Git [D]iff' },
      { '<leader>hD', 'Git [D]iff last commit' },
      { '<leader>tb', '[T]oggle git [B]lame' },
      { '<leader>tD', '[T]oggle git [D]eleted' },
    },
  },
}
